version: '3.8'

networks:
  pfcs-network:
    external: true

services:
  frontend:
    build: .
    container_name: pfcs-frontend
    ports:
      - "3001:80"
    env_file: .env
    networks:
      - pfcs-network
    restart: always
